### ISSUE TITLE
Classnames not hashing in dom

### ISSUE THREAD

**Issue by timbroder** [reactstrap/reactstrap#1049]
### Issue description

- components: `Button` (but really, global issue)
- reactstrap version `6.0.1`
- import method `/es` 
- react version `16.1.1`
- bootstrap version `4.1.1`

### What is happening?

I am trying to load bootstrap's css via modules and have webpack properly scope it (so it has hashed css class names in both the css and the dom) in my dev environment. But, webpack is only hasing the classes in the css, not the dom

### What should be happening?

This is an example of it working (not using any components from reactstrap)

![image](https://user-images.githubusercontent.com/121503/40681791-22711a3e-6358-11e8-8220-ebc48c66433c.png)

### Steps to reproduce issue

I am importing bootstrap via a css module in my `app/index.js` file:

`import 'bootstrap/dist/css/bootstrap.css';`

When I try to render a button:

```
import { Button } from 'reactstrap';
<Button color="danger">Danger!</Button>
```

I see the bootstrap css getting the proper hashes:

```css
.bootstrap__btn-danger___2Bdy9 {
  color: #fff;
  background-color: #dc3545;
  border-color: #dc3545;
}

.bootstrap__btn-danger___2Bdy9:hover {
  color: #fff;
  background-color: #c82333;
  border-color: #bd2130;
}

.bootstrap__btn-danger___2Bdy9:focus, .bootstrap__btn-danger___2Bdy9.bootstrap__focus___blrOi {
  -webkit-box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.5);
          box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.5);
}

.bootstrap__btn-danger___2Bdy9.bootstrap__disabled___2N-nG, .bootstrap__btn-danger___2Bdy9:disabled {
  color: #fff;
  background-color: #dc3545;
  border-color: #dc3545;
}
```

But, the dom remains unhashed:

```
<button class="btn btn-danger">Danger!</button>
```

I would expect it to be something like 

```
<button class="bootstrap__btn___2Bdy9 bootstrap__btn-danger___2Bdy9">Danger!</button>
```

#### Webpack

I **am** using webpack to handle the hasing, but I don't have this problem in other packages I've used that bring in their own css.

The relevant css module config from my webpack:

```
test: /\.css$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  importLoaders: 1,
                  modules: true,
                  localIdentName: "[name]__[local]___[hash:base64:5]",
                },
              },
              {
                loader: require.resolve('postcss-loader'),
                options: {
                  // Necessary for external CSS imports to work
                  // https://github.com/facebookincubator/create-react-app/issues/2677
                  ident: 'postcss',
                  plugins: () => [
                    require('postcss-flexbugs-fixes'),
                    autoprefixer({
                      browsers: [
                        '>1%',
                        'last 4 versions',
                        'Firefox ESR',
                        'not ie < 9', // React doesn't support IE8 anyway
                      ],
                      flexbox: 'no-2009',
                    }),
                  ],
                },
              },
            ],
```

#### Other things I've tried

I've also tried forcing `setGlobalCssModule`, but this did not work:

```
import bootstrap from 'bootstrap/dist/css/bootstrap.css';
setGlobalCssModule(bootstrap);
```
