### ISSUE TITLE
[Question] How to make Navbar Dark ?

### ISSUE THREAD

**Issue by AnthoniG** [reactstrap/reactstrap#544]
### Issue description
Make the Navbar component dark instead of light

- components: `Navbar`

### Steps to reproduce issue

- Set color="black" *didn't work*
- Set color="dark" *didn't work*
- Set className="navbar-dark bg-dark" *Didn't work*

How do I do it please ?
I am sure it's super simple and I am missing something obvious, but I can't find it lol.

Trying to replicate this [http://getbootstrap.com/docs/4.0/examples/dashboard/](http://getbootstrap.com/docs/4.0/examples/dashboard/)

**Comment by TheSharpieOne** [comment]
Bootstrap 4 beta was just released and reactstrap has not yet had time to make changes to support it. That being said, you should be able to use `color="dark"` and `className="navbar-dark"` or just `className="navbar-dark bg-dark"` since those classes will just simply be put onto the rendered `<div>`

Example: https://www.webpackbin.com/bins/-KrXUBuQCZUWdObRyqLs
Note: `.navbar-toggleable{-sm|-md|-lg|-xl}` has changed to `.navbar-expand{-sm|-md|-lg|-xl}` so for now you will need to add the `.navbar-expand{-sm|-md|-lg|-xl}` class yourself as I did in the example.

**Comment by AnthoniG** [comment]
@TheSharpieOne Yep, tried those as you can see above.
However it still *Didn't work*

I've kind of solved it now by fudging it.
I've imported a SCSS stylesheet that has a .header class that sets the background-color: black and color: white

This seems to work for now and I will perhaps re-vist it later :)

**Comment by TheSharpieOne** [comment]
Are you sure you are using bootstrap 4 beta? I just came out a couple of days ago. If you are not using it (and are still using alpha 6) you will not have the new classes like `navbar-dark` and such and it will not work.
If you can, create a webpackbin demonstrating your issue.

**Comment by AnthoniG** [comment]
I've downloaded the actual Bootstrap CSS and it must have been some time ago because mine says v4.0.0-alpha.6

**Comment by AnthoniG** [comment]
OK fixed that. Downloaded beta version and it now works :)
Quick Question though, whilst got you here, how do I do it for the sidebar ?
That is also a Nav item. Is there any special classes I need to know about that ?

**Comment by TheSharpieOne** [comment]
For the dashboard example, the sidebar there is just a column.

```jsx
<div>
  <Navbar color="dark" className="navbar-dark navbar-expand-sm" toggleable fixed="top">
    The navbar stuff you already have. I left it out for brevity 
  </Navbar>
  <Container fluid>
    <Row>
      <Col tag="nav" sm={3} md={2} className="d-none d-sm-block bg-light sidebar">
        <Nav pills vertical>
          <NavItem>
            <NavLink active href="#">Stuff</NavLink>
          <NavItem>
          </NavItem>
            <NavLink href="#">Stuff</NavLink>
          </NavItem>
        </Nav>
      </Col>
      <Col tag="main" sm={9} md={10} className="ml-sm-auto pt-3" role="main">
        Main Content Stuff Here
      </Col>
    </Row>
  </Container>
<div>
```
Note: the `tag` prop here just makes the DOM element something other than a `<div>`. I used it to better match the example.

The `.sidebar` class is custom for the example. Here is what the example has verbatim:

```css
/* Move down content because we have a fixed navbar that is 3.5rem tall */
body {
  padding-top: 3.5rem;
}

/*
 * Sidebar
 */

.sidebar {
  position: fixed;
  top: 51px;
  bottom: 0;
  left: 0;
  z-index: 1000;
  padding: 20px;
  overflow-x: hidden;
  overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
  border-right: 1px solid #eee;
}

/* Sidebar navigation */
.sidebar {
  padding-left: 0;
  padding-right: 0;
}

.sidebar .nav {
  margin-bottom: 20px;
}

.sidebar .nav-item {
  width: 100%;
}

.sidebar .nav-item + .nav-item {
  margin-left: 0;
}

.sidebar .nav-link {
  border-radius: 0;
}
```

Demo: https://www.webpackbin.com/bins/-Kra3figYGIyf64WK7Ze (Make sure your window is wide enough to not get the mobile view)
